name: Build and run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  net:
    name: .NET

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-13, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            8.0.x
      - name: Restore
        run: dotnet restore
      - name: Build and run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: net-test-results-${{ matrix.os }}
          path: ${{ github.workspace }}/**/tests/TestResults/*
          if-no-files-found: error
  
  net-macos-arm64:
    name: .NET macOS ARM64

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      Dotnet_X64:   "~/my-dotnet/x64"
      Dotnet_arm64: "~/my-dotnet/arm64"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Manually setup .NET 8.0, 5.0 and 3.1 SDKs
        run: >
          curl https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh -o dotnet-install.sh -s && chmod +x dotnet-install.sh && \
            ./dotnet-install.sh --architecture arm64 --skip-non-versioned-files --channel 8.0 --install-dir $Dotnet_arm64 && \
            ./dotnet-install.sh --architecture x64   --skip-non-versioned-files --channel 3.1 --install-dir $Dotnet_X64 && \
            ./dotnet-install.sh --architecture x64   --skip-non-versioned-files --channel 5.0 --install-dir $Dotnet_X64 && \
            ./dotnet-install.sh --architecture x64   --skip-non-versioned-files --channel 8.0 --install-dir $Dotnet_X64 
      - name: Restore
        run: $Dotnet_arm64/dotnet restore
      - name: Build and run arm64 tests
        run: $Dotnet_arm64/dotnet test -f net8.0 --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results_arm64'
      - name: Build and run x64 tests
        run: $Dotnet_X64/dotnet test --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results_x64'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: net-test-results-${{ matrix.os }}
          path: ${{ github.workspace }}/**/tests/TestResults/*
          if-no-files-found: error

  net-qemu:
    name: .NET QEMU

    strategy:
      fail-fast: false
      matrix:
        arch: [ s390x ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install QEMU static executables formats
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Setup .NET SDK, Restore, Build and Tests under QEMU ${{ matrix.arch }}
        run: >
          docker run --rm -v "${{ github.workspace }}:/work" --platform linux/${{ matrix.arch }} ${{ matrix.arch }}/fedora:39 /bin/bash -c " \
            dnf install -y dotnet-sdk-8.0 && \
            cd /work && \
            dotnet restore && \
            dotnet test -f net8.0 --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results' && \
            true"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: net-test-results-qemu-${{ matrix.arch }}
          path: ${{ github.workspace }}/**/tests/TestResults/*
          if-no-files-found: error

  net-self-hosted:
    name: .NET SelfHosted

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: s390x
          - os: freebsd
            arch: amd64
          - os: freebsd
            arch: arm64

    runs-on:
      - self-hosted
      - ${{ matrix.os }}
      - ${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore
        run: dotnet restore
      - name: Build and Tests
        run: dotnet test -f net8.0 --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: net-test-results-self-hosted-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/**/tests/TestResults/*
          if-no-files-found: error
