name: net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-tests:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            7.0.x
      - name: Restore
        run: dotnet restore
      - name: Build and Tests
        run: dotnet test --configuration Release --no-restore --verbosity normal

  build-and-tests-qemu:

    strategy:
      fail-fast: false
      matrix:
        arch: [ s390x ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install QEMU static executables formats
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Setup .NET SDK, Restore, Build and Tests under QEMU ${{ matrix.arch }}
        run: >
          docker run --rm -v "$(pwd):/work" --platform linux/${{ matrix.arch }} ${{ matrix.arch }}/fedora:39 /bin/bash -c " \
            dnf install -y dotnet-sdk-7.0 && \
            cd /work && \
            dotnet restore && \
            dotnet test -f net7.0 --configuration Release --no-restore --verbosity normal && \
            true"
