name: Build and run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  net:
    name: .NET

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            8.0.x
      - name: Restore
        run: dotnet restore
      - name: Build and run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: net-test-results-${{ matrix.os }}
          path: ${{ github.workspace }}/**/tests/TestResults/*
          if-no-files-found: error

  net-qemu:
    name: .NET QEMU

    strategy:
      fail-fast: false
      matrix:
        arch: [ s390x ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install QEMU static executables formats
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Setup .NET SDK, Restore, Build and Tests under QEMU ${{ matrix.arch }}
        run: >
          docker run --rm -v "${{ github.workspace }}:/work" --platform linux/${{ matrix.arch }} ${{ matrix.arch }}/fedora:39 /bin/bash -c " \
            dnf install -y dotnet-sdk-8.0 && \
            cd /work && \
            dotnet restore && \
            dotnet test -f net8.0 --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results' && \
            true"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: net-test-results-qemu-${{ matrix.arch }}
          path: ${{ github.workspace }}/**/tests/TestResults/*
          if-no-files-found: error

  net-self-hosted:
    name: .NET SelfHosted

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: s390x
          - os: freebsd
            arch: amd64
          - os: freebsd
            arch: arm64

    runs-on:
      - self-hosted
      - ${{ matrix.os }}
      - ${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore
        run: dotnet restore
      - name: Build and Tests
        run: dotnet test -f net8.0 --configuration Release --no-restore --verbosity normal --logger 'trx;LogFilePrefix=test-results'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: net-test-results-self-hosted-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/**/tests/TestResults/*
          if-no-files-found: error
